### ISSUE TITLE
user settings画面でユーザーの編集や追加をした際にエラーが発生する

### ISSUE THREAD

**Issue by Atori-Ikeyama** [Hakondate/Hakondate#155]
**概要**

- ユーザーの追加でエラー
- ユーザーの編集でエラー
- 上記のエラーを無視して続け、ドロワーを開くとエラー

**詳細**
再現方法:
1. user settings 画面でユーザーの追加又は編集

追加・編集の際のエラー文:
```
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<ScaffoldState>#08b4c]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- AppBottomNavigationBar(dependencies: [UncontrolledProviderScope, _TabPageStateProvider], state: _ConsumerState#75c8e)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack
#0      BuildOwner.finalizeTree.<anonymous closure>
framework.dart:3110
#1      BuildOwner.finalizeTree
framework.dart:3135
#2      WidgetsBinding.drawFrame
binding.dart:906
#3      RendererBinding._handlePersistentFrameCallback
binding.dart:358
#4      SchedulerBinding._invokeFrameCallback
binding.dart:1284
#5      SchedulerBinding.handleDrawFrame
binding.dart:1214
#6      SchedulerBinding._handleDrawFrame
binding.dart:1072
#10     _invoke (dart:ui/hooks.dart:144:10)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#12     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 3 frames from dart:async)
```

ドロワーを開いた際のエラー文:
```
Exception has occurred.
FlutterError (Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.)
```

**スクリーンショット**

**Flutter doctor:**

```
[✓] Flutter (Channel stable, 3.10.1, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
    • Flutter version 3.10.1 on channel stable at /Users/ikeyamayasumorisato/fvm/versions/3.10.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (6 months ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ikeyamayasumorisato/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • A18D8AD3-29BD-440F-84D6-90AF77D42839 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**発生機材:**
 - Device: [e.g. iPhone 15 Pro Max]
 - OS: [e.g. iOS17.0]

**補足事項**

- 特になし

**Comment by uwatcha** [comment]
放置されている & 優先度が低いので，Issues整理のため一旦閉じる．
