### ISSUE TITLE
新規登録画面でのバグ修正

### ISSUE THREAD

**Issue by b1017173** [Hakondate/Hakondate#44]
## 概要
新規登録画面で，文字入力中に学校選択のラベルを触るとエラーが出る（表面上は普通に動く）．

## エラーメッセージ
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:flutter/src/rendering/layer.dart': Failed assertion: line 1667 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  CupertinoPicker CupertinoPicker:file:///Users/micad/Develop/FlutterProjects/hakondate_v2/lib/view/component/setting_label.dart:48:35
When the exception was thrown, this was the stack: 
#2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1667:12)
#3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:578:13)
#4      RenderListWheelViewport._paintChildCylindrically (package:flutter/src/rendering/list_wheel_viewport.dart:975:13)
#5      RenderListWheelViewport._paintChildWithMagnifier.<anonymous closure> (package:flutter/src/rendering/list_wheel_viewport.dart:933:11)
#6      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#7      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:454:7)
#8      RenderListWheelViewport._paintChildWithMagnifier (package:flutter/src/rendering/list_wheel_viewport.dart:926:15)
#9      RenderListWheelViewport._paintTransformedChild (package:flutter/src/rendering/list_wheel_viewport.dart:861:7)
#10     RenderListWheelViewport._paintVisibleChildren (package:flutter/src/rendering/list_wheel_viewport.dart:817:7)
#11     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#12     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:454:7)
#13     RenderListWheelViewport.paint (package:flutter/src/rendering/list_wheel_viewport.dart:789:40)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#15     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#16     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#17     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#18     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#23     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#27     _invoke (dart:ui/hooks.dart:166:10)
#28     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#29     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderListWheelViewport#2ce3a
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=390.0, h=0.0)
...  layer: OffsetLayer#679fa
...    engine layer: OffsetEngineLayer#03226
...    handles: 2
...    offset: Offset(0.0, 574.4)
...  size: Size(390.0, 0.0)
RenderObject: RenderListWheelViewport#2ce3a
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=390.0, h=0.0)
  layer: OffsetLayer#679fa
    engine layer: OffsetEngineLayer#03226
    handles: 2
    offset: Offset(0.0, 574.4)
  size: Size(390.0, 0.0)
...  child 1: RenderIndexedSemantics#2ee66 relayoutBoundary=up1
...    parentData: offset=Offset(170.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=390.0, h=40.0)
...    semantic boundary
...    size: Size(50.0, 40.0)
...    index: 0
...    child: RenderParagraph#a69b3 relayoutBoundary=up2
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=390.0, h=40.0)
...      size: Size(50.0, 40.0)
...      textAlign: start
...      textDirection: ltr
...      softWrap: wrapping at box width
...      overflow: clip
...      locale: en_US
...      maxLines: unlimited
...      text: TextSpan
...        inherit: false
...        color: label(*color = Color(0xff000000)*, darkColor = Color(0xffffffff), resolved by: UNRESOLVED)
...          debugLabel: label
...          color: Color(0xff000000)
...          darkColor: Color(0xffffffff)
...        family: .SF Pro Display
...        size: 21.0
...        weight: 400
...        letterSpacing: -0.6
...        "1年生"
====================================================================================================
```

**Comment by uwatcha** [comment]
放置されている & 優先度が低いので，Issues整理のため一旦閉じる．
