### ISSUE TITLE
最初のsplashから動かないバグ

### ISSUE THREAD

**Issue by KeitaTakahashi1024** [Hakondate/Hakondate#93]
**概要**
 issue #83 をプルして起動すると、最初のsplashから動かないバグ

**詳細**
再現方法:
1. issue #83をプルする
2. アプリを起動する
3. splashからロードが終わらない

エラー文:
Launching lib/main.dart on Android SDK built for arm64 in debug mode...
Running Gradle task 'assembleDebug'...
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:529:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:573:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.addPostFrameCallback((_) {
                       ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:723:24: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                       ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:769:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:1209:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/src/pages/page_stack.dart:48:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
W/FlutterActivityAndFragmentDelegate(14696): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:53316/vEsSwQ-Z1fM=/ws
Syncing files to device Android SDK built for arm64...
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:529:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:573:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.addPostFrameCallback((_) {
                       ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:723:24: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                       ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:769:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/routemaster.dart:1209:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
../flutter/.pub-cache/hosted/pub.dartlang.org/routemaster-1.0.0/lib/src/pages/page_stack.dart:48:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^
E/flutter (14696): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'DateTime' in type cast
E/flutter (14696): #0      TypedResult.read (package:drift/src/runtime/query_builder/statements/select/select.dart:188:39)
E/flutter (14696): #1      SchoolsLocalRepository.getLatestUpdateDay.<anonymous closure> (package:hakondate/repository/local/schools_local_repository.dart:93:62)
E/flutter (14696): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter (14696): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter (14696): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
E/flutter (14696): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter (14696): #6      new List.of (dart:core-patch/array_patch.dart:51:28)
E/flutter (14696): #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter (14696): #8      _MappedSelectable._mapResults (package:drift/src/runtime/query_builder/statements/query.dart:281:64)
E/flutter (14696): #9      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (14696): #10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (14696): <asynchronous suspension>
E/flutter (14696): #11     Selectable.getSingleOrNull (package:drift/src/runtime/query_builder/statements/query.dart:230:18)
E/flutter (14696): <asynchronous suspension>
E/flutter (14696): #12     SchoolsLocalRepository.getLatestUpdateDay (package:hakondate/repository/local/schools_local_repository.dart:93:27)
E/flutter (14696): <asynchronous suspension>
E/flutter (14696): #13     SplashViewModel._initializeSchools (package:hakondate/view_model/single_page/splash_view_model.dart:85:35)
E/flutter (14696): <asynchronous suspension>
E/flutter (14696): #14     SplashViewModel.initialize.<anonymous closure> (package:hakondate/view_model/single_page/splash_view_model.dart:54:9)
E/flutter (14696): <asynchronous suspension>
E/flutter (14696): 

**スクリーンショット**
なし

**Flutter doctor:**
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm (Rosetta), locale ja-JP)
    • Flutter version 3.0.0 at /Users/keita1024/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/keita1024/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] VS Code (version 1.64.1)
    • VS Code at /Users/keita1024/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm (Rosetta)
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**発生機材:**
 - Device: [Pixel 5]
 - OS: [API 29]

**補足事項**

- 特になし

**Comment by KeitaTakahashi1024** [comment]
最新のdevelopをプルし忘れていました
